---

- name: Build Standard Fedora Workstation
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install Packages
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - vim
        - tmux
        - whois
        - telnet
        - nmap
        - htop
        - remmina
        - remmina-plugins-rdp

    - name: Update All Packages
      dnf:
        name: "*"
        state: latest

    - name: Create repo.d file for Google Chrome
      yum_repository:
        name: google-chrome
        description: google-chrome
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
        enabled: true
        gpgcheck: true
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Install Google Chrome
      dnf:
        name: google-chrome
        state: latest

    - name: Install selinux python package
      dnf:
        name: libselinux-python
        state: latest

    - name: Disable selinux
      selinux:
        state: disabled

    - name: Install .vimrc git repo
      git:
        repo: https://gist.github.com/aa74a563d2c0f67fef9a437b413ada2b.git
        dest: /opt/git/vimrc

    - name: Check for existing .vimrc
      stat:
        path: "{{ ansible_user_dir }}/.vimrc"
      register: vimrc
      changed_when: false

    - name: Delete existing .vimrc
      file:
        path: "{{ ansible_user_dir }}/.vimrc"
        state: absent
      when:
        - vimrc
        - vimrc.stat.islnk == False

    - name: Setup soft link to .vimrc
      file:
        src: /opt/git/vimrc/.vimrc
        dest: "{{ ansible_user_dir }}/.vimrc"
        state: link

    - name: Install powerbash git repo
      git:
        repo: https://github.com/napalm255/powerbash.git
        dest: /opt/git/powerbash

    - name: Setup powerbash (link script)
      file:
        src: /opt/git/powerbash/powerbash.sh
        dest: /etc/profile.d/z_powerbash.sh
        state: link

    - name: Install powerbash powertmux repo
      git:
        repo: https://github.com/napalm255/powertmux.git
        dest: /opt/git/powertmux

    - name: Setup powertmux (link script)
      file:
        src: /opt/git/powertmux/powertmux.sh
        dest: /etc/profile.d/powertmux.sh
        state: link

    - name: Setup powertmux (link tmux.conf)
      file:
        src: /opt/git/powertmux/tmux.conf
        dest: /etc/tmux.conf
        state: link

    - name: Install python packages
      pip:
        name: pip virtualenv virtualenvwrapper tldr pylint pydocstyle yamllint
        state: latest
        extra_args: --user
      become: false

    - name: Setup pip config file
      copy:
        dest: "{{ ansible_user_dir }}/.config/pip/pip.conf"
        content: |
          [list]
          format=columns
      become: false

    - name: Add 'unset SSH_ASKPASS' to bashrc
      lineinfile:
        dest: "{{ ansible_user_dir }}/.bashrc"
        line: unset SSH_ASKPASS
        state: present

    - name: Add aliases to bashrc
      lineinfile:
        dest: "{{ ansible_user_dir }}/.bashrc"
        line: "{{ item }}"
        state: present
      with_items:
        - alias vpnlogin='midori https://remote.promnetwork.com >> ~/sshtunnel.log 2>&1 &'
        - alias vpnstatus='/usr/bin/systemctl --user status sshtunnel.service'
        - alias vpnconnect='/usr/bin/systemctl --user restart sshtunnel.service'
        - alias vpndisconnect='/usr/bin/systemctl --user stop sshtunnel.service'

    - name: Add VirtualEnv variable to bashrc
      lineinfile:
        dest: "{{ ansible_user_dir }}/.bashrc"
        line: export WORKON_HOME=~/.virtualenv
        state: present

    - name: Add VirtualEnvWrapper script to bashrc
      lineinfile:
        dest: "{{ ansible_user_dir }}/.bashrc"
        line: source /usr/bin/virtualenvwrapper.sh
        state: present

    # - name: Download .vimrc from gist
    #   get_url:
    #     dest: "{{ ansible_user_dir }}/.vimrc"
    #     url: https://gist.githubusercontent.com/nobler1050/aa74a563d2c0f67fef9a437b413ada2b/raw/.vimrc
